name: Build-Sign-Push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag (e.g. v1.0.5)'
        required: true
        default: 'v1.0.0'

env:
  TAG: "${{ github.event.inputs.tag  || github.ref_name }}"
  REPO: "simpleapp"


jobs:
    build-image:
      runs-on: ubuntu-latest
  
      name: build-image
      steps:
        - uses: actions-cool/check-user-permission@7b90a27f92f3961b368376107661682c441f6103  #v2.3.0
          id: check
          with:
            username: ${{ github.triggering_actor }}
      
        - name: close
          if: ${{ steps.check.outputs.user-permission == 'read' || steps.check.outputs.user-permission == 'write' }}
          run: |
            echo -e "[!] Insuffecient Privileges\n[+] Running this action requires admin privileges!"
            exit 1

        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2

        - name: Install Cosign
          uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac  #v3.9.1
          with:
            cosign-release: 'v2.2.3'
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435  #v3.11.1
  
        - name: Login to GitHub Container Registry
          uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772  #v3.4.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_SECRET }}
              
        - name: Build and Push container images
          uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  #v6.18.0
          id: build-and-push
          with:
            context: "{{defaultContext}}:/django-app"
            platforms: linux/amd64
            push: true
            tags: zeyadabuqasem/${{ env.REPO }}:${{ env.TAG }}

        - name: Sign image
          env:
            TAGS: zeyadabuqasem/${{ env.REPO }}:${{ env.TAG }}
            COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
            DIGEST: ${{ steps.build-and-push.outputs.digest }}
          run: |
            images=""
            for tag in ${TAGS}; do
              images+="${tag}@${DIGEST}"
            done
            cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
