name: Build-Push

on:
  push

jobs:
    build-image:
      runs-on: ubuntu-latest
  
      name: build-image
      steps:
        - uses: actions/checkout@v4.1.1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_SECRET }}
              
        - name: Build and Push container images
          uses: docker/build-push-action@v5
          id: build-and-push
          with:
            platforms: linux/amd64
            push: true
            tags: zeyadabuqasem/django
